name: Build and Deploy
on:
  push:
    branches:
      - "main"
  workflow_dispatch:

permissions:
  contents: write
jobs:
  build-and-deploy:
    concurrency: ci-${{ github.ref }} # Recommended if you intend to make multiple deployments in quick succession.
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-r-dependencies@v2

      - name: Build shinylive site
        run: |
          shinylive::export(appdir="app1", destdir="build")
          shinylive::export(appdir="app2", destdir="build", subdir = "app2")
        shell: "Rscript {0}"

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: "build"
          branch: "gh-pages"
